name: Build git-annex snapshot

# TODO: include regular rule
on: [pull_request]

env:
  LANG: C
  DEB_SIGN_KEYID: 13A1093296154584245E0300C98FC49D36DAB17F

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
    - name: Set up system
      shell: bash
      run: |
        bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
        sudo apt-get update -qq
        sudo apt-get install eatmydata
        sudo eatmydata apt-get install singularity-container gnupg

    - name: Checkout this repository
      uses: actions/checkout@v1

    - name: Import GPG keys
      run: |
        # private key for signing - comes from secrets
        echo '${{ secrets.datalad_builder_gpgkey }}' | gpg --import
        # public key for verification
        cat resources/datalad-builder-key.asc | gpg --import

    - name: Building it all
      run: |
        scripts/ci/build_git_annex build

    - name: Cleanup before bundling upload
      run: find build -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 rm -rf

    - name: Upload packages
      uses: actions/upload-artifact@v2-preview
      with:
          name: git-annex-debianstandalone-packages
          # v2-preview supports globs (https://github.com/actions/upload-artifact/issues/62)
          path: build/*.*

  test-datalad:
    runs-on: ubuntu-latest
    needs: build-package
    strategy:
      matrix:
        version: [master, maint, release]
      fail-fast: false

    steps:
      - name: Download git-annex package
        uses: actions/download-artifact@v2-preview
        with:
          name: git-annex-debianstandalone-packages

      - name: Install git-annex package
        run: |
          ls -l
          sudo dpkg -i *.deb

      - name: Set up environment
        run: |
          git config --global user.email "test@github.land"
          git config --global user.name "GitHub Almighty"

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install ${{ matrix.version }} datalad
        run: |
          if [ "${{ matrix.version }}" = "release" ]; then
            commitish=$(curl -s https://api.github.com/repos/datalad/datalad/releases/latest | awk '/"tag_name"/{print $2}' | sed -e 's,[",],,g');
          else
            commitish="${{ matrix.version }}";
          fi
          python -m pip install --upgrade pip
          pip install https://github.com/datalad/datalad/archive/${commitish}.zip

      - name: Install nose et al (just in case!)
        run: |
          pip install nose vcrpy mock

      - name: WTF!?
        run: |
          datalad wtf

      - name: Run datalad tests
        run: |
          mkdir -p __testhome__
          cd __testhome__
          python -m nose -s -v datalad
