name: Extensions

on:
  schedule:
    - cron: '30 01 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        extension: [
            datalad_neuroimaging,
            datalad_container,
            datalad_metalad,
            datalad_crawler,
            # datalad_webapp,     # not developed ATM, not sure if of interest to keep track
            # datalad_ukbiobank,  # yet to be renamed (issue filed), has no tests, so would fail
        ]
    steps:
    - name: Set up system
      shell: bash
      run: |
        bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
        sudo apt-get update -qq
        sudo apt-get install eatmydata
        sudo eatmydata apt-get install git-annex-standalone
    - name: Set up environment
      run: |
        git config --global user.email "test@github.land"
        git config --global user.name "GitHub Almighty"
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install DataLad (master)
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/datalad/datalad/archive/master.zip
    - name: Install ${{ matrix.extension }} extension ([devel])
      run: |
        pip install ${{ matrix.extension }}[devel]
    - name: Install nose et al (just in case!)
      run: |
        pip install nose vcrpy mock
    - name: Install Singularity
      run: sudo eatmydata apt-get install singularity-container
      if: matrix.extension == 'datalad_container'
    - name: WTF!?
      run: |
        datalad wtf
    - name: ${{ matrix.extension }} tests
      run: |
        mkdir -p __testhome__
        cd __testhome__
        python -m nose -s -v --with-cov --cover-package datalad ${{ matrix.extension }}
